// Code generated by "stringer -type=InternalState"; DO NOT EDIT.

package errs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mochasippi-0]
	_ = x[Breve-1]
	_ = x[Papi-2]
	_ = x[Instant-3]
	_ = x[Turkish-4]
	_ = x[Irish-5]
	_ = x[Crema-6]
	_ = x[Cappuccino-7]
	_ = x[Unknown-8]
	_ = x[Latte-9]
	_ = x[Flatwhite-10]
	_ = x[Melange-11]
	_ = x[Cortado-12]
	_ = x[Galao-13]
	_ = x[Kopisusu-14]
	_ = x[Affogato-15]
	_ = x[Macchiato-16]
	_ = x[Bicerin-17]
	_ = x[Bombón-18]
	_ = x[Mocha-19]
	_ = x[Caphesuada-20]
	_ = x[Carajillo-21]
	_ = x[Espresso-22]
	_ = x[Eiskaffee-23]
	_ = x[Frappuccino-24]
	_ = x[Iced-25]
	_ = x[Indianfilter-26]
	_ = x[Kopiluwak-27]
	_ = x[Kopitubruk-28]
	_ = x[Vienna-29]
	_ = x[Yuanyang-30]
	_ = x[None-31]
	_ = x[Americano-32]
	_ = x[Cubano-33]
	_ = x[Zorro-34]
	_ = x[Doppio-35]
	_ = x[Romano-36]
	_ = x[Guillermo-37]
	_ = x[Ristretto-38]
	_ = x[Antoccino-39]
	_ = x[Aulait-40]
	_ = x[Kula-41]
	_ = x[Melya-42]
	_ = x[Marocchino-43]
	_ = x[Miel-44]
	_ = x[Mazagran-45]
	_ = x[Palazzo-46]
	_ = x[Medici-47]
	_ = x[Touba-48]
	_ = x[Pocillo-49]
	_ = x[Misto-50]
	_ = x[Coldbrew-51]
}

const _InternalState_name = "MochasippiBrevePapiInstantTurkishIrishCremaCappuccinoUnknownLatteFlatwhiteMelangeCortadoGalaoKopisusuAffogatoMacchiatoBicerinBombónMochaCaphesuadaCarajilloEspressoEiskaffeeFrappuccinoIcedIndianfilterKopiluwakKopitubrukViennaYuanyangNoneAmericanoCubanoZorroDoppioRomanoGuillermoRistrettoAntoccinoAulaitKulaMelyaMarocchinoMielMazagranPalazzoMediciToubaPocilloMistoColdbrew"

var _InternalState_index = [...]uint16{0, 10, 15, 19, 26, 33, 38, 43, 53, 60, 65, 74, 81, 88, 93, 101, 109, 118, 125, 132, 137, 147, 156, 164, 173, 184, 188, 200, 209, 219, 225, 233, 237, 246, 252, 257, 263, 269, 278, 287, 296, 302, 306, 311, 321, 325, 333, 340, 346, 351, 358, 363, 371}

func (i InternalState) String() string {
	if i < 0 || i >= InternalState(len(_InternalState_index)-1) {
		return "InternalState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InternalState_name[_InternalState_index[i]:_InternalState_index[i+1]]
}
